// <auto-generated />
using BlazorApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("BlazorApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "American"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chinese"
                        });
                });

            modelBuilder.Entity("BlazorApp.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nachos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tacos"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Noodles"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sushi"
                        });
                });

            modelBuilder.Entity("CategoryFood", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "FoodsId");

                    b.HasIndex("FoodsId");

                    b.ToTable("CategoryFood");
                });

            modelBuilder.Entity("CategoryFood", b =>
                {
                    b.HasOne("BlazorApp.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
